services:
  nginx-quiche:
    build: nginx-quiche
    expose:
      - "443/tcp"
      - "443/udp"
    volumes:
      - "./nginx-quiche/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx-quiche/docroot:/var/www/html:ro"
      - "./server.crt:/etc/nginx/cert.crt:ro"
      - "./server.key:/etc/nginx/cert.key:ro"
  curl-quiche:
    build: curl-quiche
    depends_on:
      - nginx-quiche
    command: curl -kv --http3 https://nginx-quiche
volumes:
  nginx-quiche-docroot: {}
